FortressOfSolitude/_FortressOfSolitude/organizer/urls.py
'''
DBA 1337_TECH, AUSTIN TEXAS © MAY 2020
Proof of Concept code, No liabilities or warranties expressed or implied.
'''

from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from .views import tag_detail, tasking_detail, TagCreate, TaskingCreate, \
    UploadFile, TaskingList, TagList, TaskingUpdate, SuccessView, DownloadImageList, \
    DownloadTheGoodsView, DownloadMusicList, DownloadTheMusicalGoodsView  # , task_status

urlpatterns = [
                  url(r'^$',
                      login_required(TagList.as_view()),
                      name='organizer_tag_list'),
                  url(r'^tag/create/$',
                      login_required(TagCreate.as_view()),
                      name='organizer_tag_create'),
                  url(r'^tasking/create/$',
                      login_required(TaskingCreate.as_view()),
                      name='organizer_tasking_create'),
                  url(r'^tag/(?P<slug>[\w\-]+)/$',
                      tag_detail,
                      name='organizer_tag_detail'),
                  url(r'^tasking/(?P<slug>[\w\-]+)/$',
                      tasking_detail,
                      name='organizer_tasking_detail'),
                  url(r'^create/$',
                      login_required(TagCreate.as_view()),
                      name='organizer_tag_create'),
                  url(r'^upload/create/$',
                      login_required(UploadFile.as_view()),
                      name='organizer_upload_create'),
                  url(r'^upload/create/uploadsuccess/$',
                      login_required(SuccessView.as_view()),
                      name='organizer_upload_success'),
                  url(r'^tasking/$',
                      login_required(TaskingList.as_view()),
                      name='organizer_tasking_list'),
                  url(r'^(?P<slug>[\w\-]+)/update/$',
                      login_required(TaskingUpdate.as_view()),
                      name='organizer_tasking_update'),
                  url(r'^download/$',
                      login_required(DownloadImageList.as_view()),
                      name='organizer_download_pull'),
                  url(r'^download/music/$',
                        login_required(DownloadMusicList.as_view()),
                        name='organizer_music_download_pull'),
                  url('^download/media/photos/(?P<pk>\d+)$',
                      login_required(DownloadTheGoodsView.as_view()),
                      {'document_root': settings.MEDIA_ROOT}),
                  url('^download/music/media/music/(?P<pk>\d+)$',
                      login_required(DownloadTheMusicalGoodsView.as_view()),
                      {'document_root': settings.MEDIA_ROOT}),
                  # re_path(r'^download/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_ROOT}),
                  # url(r'^(?P<task_id>[\w-]+)/$', task_status, name='task_status')
              ] + static('/media/', document_root=settings.MEDIA_ROOT)

FortressOfSolitude/_FortressOfSolitude/superhero/urls.py
"""
DBA 1337_TECH, AUSTIN TEXAS © MAY 2021
Proof of Concept code, No liabilities or warranties expressed or implied.
"""

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import RedirectView

# TODO: Create a RegisterCreate View

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='dj-auth:login', permanent=False)),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='superhero/logged_out.html',
                                                    extra_context={'form': AuthenticationForm}),
        name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='superhero/login.html'), name='login'),
    # url(r'^register/$', RegisterCreate.as_view(), name='register_create'),

]

FortressOfSolitude/_FortressOfSolitude/urls.py
"""
_FortressOfSolitude URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/

Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

# Uncomment next two lines to enable admin:
from django.conf.urls import include, url

from _FortressOfSolitude.Blog import urls as blog_urls
from _FortressOfSolitude.Blog.views import PostList
from _FortressOfSolitude.organizer import urls as organizer_urls
from _FortressOfSolitude.superhero import urls as superhero_urls

urlpatterns = [
    # Uncomment the next line to enable the admin:
    # path('admin/', admin.site.urls),
    url(r'^', include(organizer_urls)),
    url(r'^$', PostList.as_view()),
    url(r'^superhero/', include((superhero_urls, 'superhero'), namespace='dj-auth')),
    url(r'^blog/', include(blog_urls)),
    ]

FortressOfSolitude/_FortressOfSolitude/organizer/forms.py
'''
DBA 1337_TECH, AUSTIN TEXAS © MAY 2020
Proof of Concept code, No liabilities or warranties expressed or implied.
'''


from django import forms
from django.core.exceptions import ValidationError
from .models import NewsLink, Startup, Tag, Tasking, Librarian
from datetime import datetime

class NewsLinkForm(forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = '__all__'

class SlugCleanMixin:
    """Mixin class for slug cleaning method. """

    def clean_slug(self):
        new_slug = (self.cleaned_data['slug'].lower())
        if new_slug == 'create':
            raise ValidationError('Slug may not be "create".')
        return new_slug

class StartupForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Startup
        fields = '__all__'

class TagForm(SlugCleanMixin, forms.Form):
    name = forms.CharField(max_length=32)
    slug = forms.SlugField(max_length=32, help_text='A label for URL config')

    class Meta:
        model = Tag
        fields = '__all__'

    def save(self):
        new_tag = Tag.objects.create(name=self.cleaned_data['name'],
                                     slug=self.cleaned_data['slug'])
        return new_tag

    def clean_name(self):
        return self.cleaned_data['name'].lower()

class TaskingForm(SlugCleanMixin, forms.ModelForm):

    #name = forms.CharField(max_length=32)
    #slug = forms.SlugField(max_length=32, help_text='A label for URL config')
    #asignee = forms.CharField(max_length=16, help_text='who is creating the task?')
    #project_codename = forms.CharField(max_length=32, help_text='project name (codename)')
    #description = forms.Textarea()
    #assigned_date = forms.DateTimeField(initial=datetime.now())#make into an automatically generated field and read-only

    class Meta:
        model = Tasking
        fields = '__all__'

    #def save(self):
    #    new_task = Tasking.objects.create(name=self.cleaned_data['name'],
    #                                      slug=self.cleaned_data['slug'],
    #                                      asignee=self.cleaned_data['asignee'],
    #                                      project_codename=self.cleaned_data['project_codename'],
    #                                      description=self.cleaned_data['description'],
    #                                      assigned_date=self.cleaned_data['assigned_date'])
    #    return new_task

    def clean_name(self):
        return self.cleaned_data['name'].lower()

class UploadFileForm(SlugCleanMixin,forms.Form):
    title = forms.CharField(max_length=32)
    file = forms.FileField()
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>
        {% block title %}
        Startup Organizer
        {% endblock %}
    </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrom=1" />
    <meta name=" = viewport" content="width=device-width, iniital-scale=1" />
    <style>
        nav {
            font-size: 100%;
            position: fixed;
            top: 0;
            width: 100%; 
            background:  #CC0000 !important;
            overflow: hidden;
            margin: 0;
            padding: 0;
            border: 4px solid darkred;
            border-radius: 4px;
        }
        nav a {
            float: left;
            text-decoration: none;
            padding: 14px 23px;
        }

            nav a:hover {
                background-color: #820000;
                
            }

       ul.stayClassySanDiego {
           list-style-type: none;
            font-size: 100%;
            position: fixed;
            right: 0;
            height: 100%; 
            width: 121px;
            background:  #276CE8 !important;
            overflow: hidden;
            margin: 85px 0px 0px 0px;
            padding: 0px;
            border: 3px solid #75A1F1;
            border-radius: 5px;
            
            }
            ul.stayClassySanDiego li a {
                    float: left;
                    text-decoration: none;
                    padding: 5px 5px;
                    
                    
                }
             ul.stayClassySanDiego li a:hover {
                    background-color: #194595;
                    width: 100%;
                    border-radius: 7px;
                }

        footer.bottomFooter {
            position: fixed;
            bottom: 0;
            width: 100%;
            background-color: yellow;
            border: 4px solid #CCCC00;
            border-radius: 5px;

        }

    </style>
</head>
<body style="background-color: #A7C3F6;margin:0;"> <!-- chartreuse -->
        <div class="container" align="center" >
             <div class="container" align="left">
                <ul class="stayClassySanDiego">
                    <li><a href="{% url 'organizer_tag_create' %}"><h><font face="verdana" style="font-weight:bold;" color="Black">Tagging</font></h></a></li>
                    <li><a href="{% url 'organizer_tasking_create' %}"><h><font face="verdana" style="font-weight:bold;" color="Black">Tasking</font></h></a></li>
                </ul>
            </div>
            <div class="container navbar-right" >
                <nav>
                        <a class="navbar-item" text-align="center">
                            <img src="{% static "img/fortressOfSolitude.png" %}" alt="Do_You_Have_The_Strength?" width="121" height="75" />
                        </a>
                        <a class="navbar-item" text-align="center" href="{% url 'organizer_upload_create' %}">
                           <h1 align="center"><font color="white">Fortress of Solitude</font></h1>
                        </a>

                        <a href="{% url 'organizer_tag_list' %}"><h1><font color="white">    TagList   </font> </h1></a>

                        <a href="{% url 'organizer_tasking_list' %}"><h1><font color="white">   TaskList   </font> </h1></a>
                         <a href="{% url 'blog_post_list' %}"><h1><font color="white">   Blog   </font> </h1></a>
                        </a>
                </nav>
            </div>
           
      </div>
    
    <div  style="padding:20px;margin-top:30px;"></div>
    <main>
        {% block content %}
        This is default content!
        {% endblock %}
    </main>

    <div class="status row">
      <div class="offset-by-eight four columns">
        <ul class="inline" style="list-style-type: none;">
          {% if user.is_authenticated %}
          <li><a href="{% url 'dj-auth:logout' %}?
                 next={{ request.path }}">
            Log Out</a></li>
            {% else %}
            <li><a href="{% url 'dj-auth:login' %}?
                   next={{ request.path }}">
              Log In</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
    <div><!-- container-->
        <footer class="bottomFooter" >
            <p align="center">
                &copy; 2019
                <a href="TBD.com"> LEET_TECH</a>
            </p>
        </footer>
    </div>
    
</body>
</html>

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/imagefile_list.html
{% extends parent_template|default:"organizer/base.html" %}
{% load static %}

{% block title %}
{{ block.super }}  - {{ imagefile.name|title }}
{% endblock %}

{% block content %}

<h2> Download List<!-- name of download List --> </h2>
    <div class="col-lg-8 d-lg-block">

    </div>
        <ul>
            <!-- list of startups related to tag-->
            <div class="row">
                {% for file in imagefile_list %}

                {% if forloop.counter|divisibleby:4 %}
                <div class="col-xs-12 shelf" style="column-fill:balance;"></div>
                {% endif %}
                    <decrypt>
                        <a class="shelfurl" style="position:relative;width:100%"href="media/photos/{{ file.id }}">
                                <span data-title="{{ file|title }}">
                                <img src="{% static 'img/NuclearAdjusted.png' %}" width="100" height="150" style="background-color:steelblue;position:relative;" class="img-responsive comicBook" alt="" />
                                <h2 class="comicBookTitle">{{ file|title}}</h2>
                                </span>
                        </a>
                    </decrypt>
               
                
                {% empty %}
                <li><em>There are currently no Downloads availiable</em></li>
                {% endfor %}
                <div class="col-xs-12 shelf" style="column-fill:balance;"></div>
            </div>
        </ul>
{% endblock %}

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/index.html
<html>
<head><title></title></head>

<body>

{{ content }}

</body>
</html>

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/startup_detail.html
{% extends parent_template|default:"organizer/base.html" %}

{% block title %}
{{ block.super }}  - {{ Startup.name|title }}
{% endblock %}

{% block content %}


<h2> {{Startup.name}}<!-- name of Startup --> </h2>
{% if Startup.blog_posts.all %}
    <section>
        <h3>Startups</h3>
        <u1>
            <!-- list of startups related to Startup-->
            {% for startup in Startup.blog_posts.all %}
            <li><a href="{{ startup.get_absolute_url }}">
                {{startup.name}}
            </a></li>
            {% endfor %}
        </u1>
    </section>
{% else %}
    <p>This Startup is not related to any startups.</p>
{% endif %}
  {% if Startup.blog_posts.all %}
<section>
    <h3>Blog Posts</h3>
    <u1>
        <!-- list of posts related to Startup -->
        {% for post in Startup.blog_posts.all %}
        <li><a href="{{ post.get_absolute_url }}">
            {{post.title|title}}
            </a></li>
        {% endfor %}
    </u1>
</section>
{% endif %}
{% if not Startup.startup_set.all and not Startup.blog_posts.all %}
    <p>This Startup is not related to any content.</p>
{% endif %}

{%endblock %}

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/startup_form.html
{% extends parent_template|default:"organizer/base.html" %}

{% block title %}
{{ block.super }} - Create Startup
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{% url 'organizer_startup_create' %}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="CreateButton" type="submit">
          Create Startup </button>
      </form>
    </div>
  </div>
{% endblock %}

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base.html" %}

{% block title %}
{{ block.super }}  - {{ startup.name|title }}
{% endblock %}

{% block content %}

<h2> TagList<!-- name of tag --> </h2>
    <div class="col-lg-8 d-lg-block">

        <a href="{% url 'organizer_startup_create' %}">Create a New Startup</a>
    </div>
        <ul>
            <!-- list of startups related to tag-->

                {% for startup in startup_list %}
                <li><a href="{{ startup.get_absolute_url }}">
                    {{ startup.name|title}}
                </a></li>
                {% empty %}
                <li><em>There are currently no Startup availiable</em></li>
                {% endfor %}
        </ul>

{% endblock %}

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base.html" %}

{% block title %}
{{ block.super }}  - {{ tag.name|title }}
{% endblock %}

{% block content %}


<h2> {{tag.name}}<!-- name of tag --> </h2>
{% if tag.startup_set.all %}
    <section>
        <h3>Startups</h3>
        <u1>
            <!-- list of startups related to tag-->
            {% for startup in tag.startup_set.all %}
            <li><a href="{{ startup.get_absolute_url }}">
                {{startup.name}}
            </a></li>
            {% endfor %}
        </u1>
    </section>
{% else %}
    <p>This tag is not related to any startups.</p>
{% endif %}
  {% if tag.blog_posts.all %}
<section>
    <h3>Blog Posts</h3>
    <u1>
        <!-- list of posts related to tag -->
        {% for post in tag.blog_posts.all %}
        <li><a href="{{ post.get_absolute_url }}">
            {{post.title|title}}
            </a></li>
        {% endfor %}
    </u1>
</section>
{% endif %}
{% if not tag.startup_set.all and not tag.blog_posts.all %}
    <p>This tag is not related to any content.</p>
{% endif %}

{%endblock %}

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base.html" %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}

    <form action="{% url 'organizer_tag_create' %}"
          method="post">
        {% csrf_token %}
        <h2> Create Tag<!-- name of tag --> </h2>
        <p>
            <label for="id_name">Name:</label>
            <input id="id_name" maxlength="32"
                   name="name" type="text" />
            <span class="helptext">
                A label for URL config
            </span>
        </p>
        <p>
            <label for="id_slug">Slug:</label>
            <input id="id_slug" maxlength="32" name="slug" type="text" />
            <span class="helptext">A label for URL config</span>
        </p>
        <button type="submit"> Create Tag </button>
    </form>
{% endblock %}

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base.html" %}

{% block title %}
{{ block.super }}  - {{ tag.name|title }}
{% endblock %}

{% block content %}

<h2> TagList<!-- name of tag --> </h2>
    <div class="col-lg-8 d-lg-block">

        <a href="{% url 'organizer_tag_create' %}">Create a New Tag</a>
    </div>
        <ul>
            <!-- list of startups related to tag-->

                {% for tag in tag_list %}
                <li><a href="{{ tag.get_absolute_url }}">
                    {{ tag.name|title}}
                </a></li>
                {% empty %}
                <li><em>There are currently no Tags availiable</em></li>
                {% endfor %}
        </ul>
        
{% endblock %}

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/tasking_form.html
{% extends parent_template|default:"organizer/base.html" %}

{% block title %}
{{ block.super }} - Create Task
{% endblock %}

{% block content %}

{% if perms.organizer.add_tasking %}
    <h2> Create Task<!-- name of tag --> </h2>

    <form action="{% url 'organizer_tasking_create' %}"
          method="post">
        {% csrf_token %}
        <p>
            <label for="id_name">Name:</label>
            <input id="id_name" maxlength="32"
                   name="name" type="text" />
            <span class="helptext">
                Name Field
            </span>
        </p>
        <p>
            <label for="id_slug">Slug:</label>
            <input id="id_slug" maxlength="32" name="slug" type="text" />
            <span class="helptext">Slug Field</span>
        </p>

        <p>
            <label for="id_asignee">Asignee:</label>
            <input id="id_asignee" maxlength="16"
                   name="asignee" type="text" />
            <span class="helptext">
               Asignee Field
            </span>
        </p>
         <p>
            <label for="id_project_codename">Codename:</label>
            <input id="id_project_codename" maxlength="16"
                   name="project_codename" type="text" />
            <span class="helptext">
               Codename
            </span>
        </p>
        <p>
            <label for="id_description">Description:</label>
            <textarea cols="35" rows="8" maxlength="128" name="description" type="text" ></textarea>
            <span class="helptext">Description Field</span>
        </p>

        <p>
            <label for="id_assigned_date">Assigned Date:</label>
            <input id="id_assigned_date" name="assigned_date" type="datetime-local" value="{% now 'Y-m-d h:i:s' %}" />
            
            <span class="helptext">A label for URL config</span>
        </p>
        <button type="submit"> Create Task </button>
    </form>
{% else %}
<h2>YOU DON't have permissions</h2>
{% endif %}
{% endblock %}

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/tasking_form_update.html
{% extends parent_template|default:"organizer/base.html" %}
{% load display_form %}

{% block title %}
{{ block.super }} - Update Tasking
{% endblock %}

{% block content %}
  {% form tasking.get_update_url 'Update Tasking' %}
{% endblock %}

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/tasking_list.html
{% extends parent_template|default:"organizer/base.html" %}

{% block title %}
{{ block.super }}  - {{ tasking.name|title }}
{% endblock %}

{% block content %}

<h2> TaskingList<!-- name of tag --> </h2>
    <div>
        <!-- <a href="{% url 'organizer_tag_create' %}">Create a New Tag</a> -->
        <a href="{% url 'organizer_tasking_create' %}">Create a new Task</a>
    </div>
        <ul>
            <!-- list of startups related to tag-->
            {% for tasking in tasking_list %}
            <li><a href="{{ tasking.get_absolute_url }}">
                {{ tasking.name|title}}
            </a></li>
            {% empty %}
            <li><em>There are currently no Taskings availiable</em></li>
            {% endfor %}
        </ul>

        {% if perms.organizer.add_tasking or perms.ogranizer.delete_tasking %}
          <ul class="inline">
          {% if perms.organizer.add_tasking %}
            <li>
              <a
                  href="{{ tasking.get_update_url }}"
                  class="button">
                Edit Tag</a></li>
            {% endif %}
          </ul>
{% endif %}
{% endblock %}

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/upload.html
{%extends parent_template|default:"organizer/base.html" %}

{% block title %}
{{ block.super }} - Upload
{% endblock %}

{% block content %}
<div class="row">
  <div align="center" class="offset-by-two five columns">
    {% include "organizer/upload_form.html" %}
  </div>
</div>
{% endblock %}

FortressOfSolitude/_FortressOfSolitude/organizer/templates/organizer/upload_form.html
{% block content %}
<form enctype="multipart/form-data"
      method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
        Upload
    </button>
</form>

{% endblock %}